### ISSUE TITLE
Benchmark Updates?

### ISSUE THREAD

**Issue by tobias992** [NickMRamirez/Proxy-Benchmarks#8]
Hi,

thank you very much for this benchmarks. You plan to make an update with actual versions? E.g. caddy gets some nice performance improvements - specially in 2.6.0. You also plan to make a test for https offloading performance?

**Comment by NickMRamirez** [comment]
Thanks for the reminder. I have updated the Docker images to the latest versions of each proxy and re-run the tests, and recorded the results in the README. 

I do like the idea of testing HTTPS offloading, but I think it will require a more complex setup because I would need to ensure that the TLS certificate was in place, with a valid domain + DNS record, and then learn how to configure each proxy. I'm not saying it's an impossible task, but it would take some time to figure out. If others have the terraform code to set such a thing up, contributions are welcomed. :-) 

For now, I will probably keep this simply HTTP routing.
